project:
  type: website

website:
  page-navigation: true
  title: "QualCoder Workshop"
  site-url: "https://ucsb-library-research-data-services.github.io/qualcoder-workshop/"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    background: "#A7D5E8"
    right:
    - text: "License"
      href: LICENSE.md
    - text: "Code of Conduct"
      href: CODE_OF_CONDUCT.md

  navbar:
    background: "#A7D5E8"
    align: center
    title: false
    collapse-below: lg

    right:
      - icon: github
        href: https://github.com/UCSB-Library-Research-Data-Services/qualcoder-workshop
        aria-label: GitHub
      - icon: book
        href: https://qualcoder.org/doc/en/
        aria-label: QualCoder documentation

    left:
      - text: "Overview"
        href: index.qmd
      - text: "Episodes"
        href: episodes.qmd
      - text: "Wrap-up"
        href: wrap-up.qmd
      - text: "Reference"
        href: reference.qmd

  sidebar:
    - id: overview
      title: "Overview"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: index.qmd
          text: "Welcome"
        - href: 00-agenda.qmd

    - id: episodes
      title: "Episodes"
      contents:
        - href: episodes.qmd
        - href: 01-meet-qualcoder.qmd
        - href: 02-set-up-project.qmd
        - href: 03-code-your-data.qmd
        - href: 04-analyze-report.qmd
        - href: 05-ai-features.qmd
        - href: wrap-up.qmd

    - id: reference
      title: "Reference"
      contents:
        - href: reference.qmd
        - href: ref-teamwork.qmd
        - href: ref-imports-exports.qmd
        - href: ref-under-the-hood.qmd
        - href: ref-sources.qmd

format:
  html:
    theme:
      light: [cosmo, style/workshop.scss]
      dark: [cosmo, style/workshop.scss, style/dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    include-in-header: "style/fontawesome.html"

freeze: auto

editor: visual
